//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portfolio.Ressourcen {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("portfolio.Ressourcen.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        internal static string pageTitle {
            get {
                return ResourceManager.GetString("pageTitle", resourceCulture);
            }
        }
        
        internal static string navHome {
            get {
                return ResourceManager.GetString("navHome", resourceCulture);
            }
        }
        internal static string navAbout {
            get {
                return ResourceManager.GetString("navAbout", resourceCulture);
            }
        }
        internal static string navSkills {
            get {
                return ResourceManager.GetString("navSkills", resourceCulture);
            }
        }
        internal static string navProjects {
            get {
                return ResourceManager.GetString("navProjects", resourceCulture);
            }
        }
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcomeTitle", resourceCulture);
            }
        }
        internal static string welcomeText {
            get {
                return ResourceManager.GetString("welcomeText", resourceCulture);
            }
        }
        internal static string welcomeText2 {
            get {
                return ResourceManager.GetString("welcomeText2", resourceCulture);
            }
        }
        internal static string welcomeText3 {
            get {
                return ResourceManager.GetString("welcomeText3", resourceCulture);
            }
        }
        internal static string aboutText {
            get {
                return ResourceManager.GetString("aboutText", resourceCulture);
            }
        }
        internal static string aboutText2 {
            get {
                return ResourceManager.GetString("aboutText2", resourceCulture);
            }
        }
        internal static string aboutText3 {
            get {
                return ResourceManager.GetString("aboutText3", resourceCulture);
            }
        }
        internal static string passionate1 {
            get {
                return ResourceManager.GetString("passionate1", resourceCulture);
            }
        }
        internal static string passionate2 {
            get {
                return ResourceManager.GetString("passionate2", resourceCulture);
            }
        }
        internal static string passionate3 {
            get {
                return ResourceManager.GetString("passionate3", resourceCulture);
            }
        }
        internal static string aboutText4 {
            get {
                return ResourceManager.GetString("aboutText4", resourceCulture);
            }
        }
        internal static string learn {
            get {
                return ResourceManager.GetString("learn1", resourceCulture);
            }
        }
        internal static string learn2 {
            get {
                return ResourceManager.GetString("learn2", resourceCulture);
            }
        }
        
        internal static string learn3 {
            get {
                return ResourceManager.GetString("learn3", resourceCulture);
            }
        }
        internal static string aboutText5 {
            get {
                return ResourceManager.GetString("aboutText5", resourceCulture);
            }
        }
        internal static string tech {
            get {
                return ResourceManager.GetString("tech1", resourceCulture);
            }
        }
        internal static string tech2 {
            get {
                return ResourceManager.GetString("tech2", resourceCulture);
            }
        }
        
        internal static string tech3 {
            get {
                return ResourceManager.GetString("tech3", resourceCulture);
            }
        }
        internal static string tech4 {
            get {
                return ResourceManager.GetString("tech4", resourceCulture);
            }
        }
        internal static string companyText {
            get {
                return ResourceManager.GetString("companyText", resourceCulture);
            }
        }
    }
}
